### ISSUE TITLE
[BUG] Démarrage

### ISSUE THREAD

**Issue by Mioultigaming** [billythegoat356/Zodiac#1]
Bonjour,
au démarrage du script python, il me fait une erreur :
```
**C:\Users\*******\Desktop\Dev\Zodiac-main>py main.py**
Traceback (most recent call last):
  File "C:\Users\*******\Desktop\Dev\Zodiac-main\main.py", line 2, in <module>
    from flask import Flask, request, send_file, redirect
ModuleNotFoundError: No module named 'flask'
```
J'ai dont fait :
`pip install -U Flask`
Mais toujours en lançant le script, il me ressort la même erreur.

Merci

**Comment by billythegoat356** [comment]
Bonjour,
Si vous avez installé le module mais avez toujours une erreur de module manquant, c'est probablement parce que vous avez plusieurs python sur votre machine.
Essayez de faire `python -m pip install flask` puis `python main.py`.

**Comment by Mioultigaming** [comment]
Merci d'avance ! Mais maintenant voilà ce qu'il me fait :

https://user-images.githubusercontent.com/52372852/151664262-86df31fd-15af-4961-9a94-f20d7c7bea33.mp4


Je vous remercie !

**Comment by billythegoat356** [comment]
Il faut que tu appuies sur entrée.

**Comment by Mioultigaming** [comment]
Merci ! Tout marches !
