### ISSUE TITLE
No requirements.txt file

### ISSUE THREAD

**Issue by oyedejioyewole** [billythegoat356/Zodiac#2]
I tried scanning around the project for a bit, and I didn't discover any `requirements.txt` or `project library` files.

Surely I definitely see you use `Flask` in the `main.py` but I can't see a file you can use to install the dependencies
for this project

**Comment by billythegoat356** [comment]
You just have to pip install it...

**Comment by oyedejioyewole** [comment]
I think I will generate a `requirements.txt` file and create a pull request with that file to have at least a decent foundation for installing packages
